// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUmA4sKdl4nv-cYd2Gm7hF9P_dFgMZ5uw',
    appId: '1:360428456810:web:587ec5a6920410fb19f313',
    messagingSenderId: '360428456810',
    projectId: 'plantapp-88a7a',
    authDomain: 'plantapp-88a7a.firebaseapp.com',
    storageBucket: 'plantapp-88a7a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPqxYiYdf26OlGhFnG-FtcQFRsiD2sImM',
    appId: '1:360428456810:android:1a50691a81fcef8119f313',
    messagingSenderId: '360428456810',
    projectId: 'plantapp-88a7a',
    storageBucket: 'plantapp-88a7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjjyr93_zs7jUWjFpxp6t4S3DXyJbGwG8',
    appId: '1:360428456810:ios:b38db77e5339bf1319f313',
    messagingSenderId: '360428456810',
    projectId: 'plantapp-88a7a',
    storageBucket: 'plantapp-88a7a.appspot.com',
    iosBundleId: 'com.example.plantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjjyr93_zs7jUWjFpxp6t4S3DXyJbGwG8',
    appId: '1:360428456810:ios:b38db77e5339bf1319f313',
    messagingSenderId: '360428456810',
    projectId: 'plantapp-88a7a',
    storageBucket: 'plantapp-88a7a.appspot.com',
    iosBundleId: 'com.example.plantApp',
  );
}
